### PR TITLE
Script for searching GitHub for Datalad repos

### LINKED ISSUE #1: Populate from github search results
It is pretty much a regular drill that we either out of curiosity or for reporting purposes run search queries on github to detect possible usages of DataLad and `datalad run` in particular.  Many of our own projects "pollute" the results making it difficult to "filter out" for new hits.

<details>
<summary>  Here is e.g. a list from fresh discussion on Riot</summary> 

Datalad code in python-neo: https://github.com/NeuralEnsemble/python-neo/search?q=datalad
Cool: https://github.com/cryo-data/QGreenland
https://github.com/neuropoly/data-management
https://github.com/htwangtw/publiccrawler
https://github.com/Raj-Lab-UCSF/Human_Brain_Atlases
The donders has started using datalad: https://github.com/Donders-Institute-Data/dcc.DSC_2018.00127_973_v1 (there are more)

-> https://github.com/topics/datalad

a whole slew of individual datasets, e.g. https://github.com/sappelhoff/eeg_matchingpennies
https://github.com/SIMEXP/fmriprep-reproducibility
https://github.com/connectomicslab/CMTKLIB-data

and some use datalad run if you search up for RUNCMD and filter out "ours", e.g. https://github.com/neurostuff/simulate-cbma https://github.com/lnnrtwttkhn/tools https://github.com/PennSIVE/agespan7t
would be neat to somehow establish a "news feed" for new hits!?
</details>

I think in the fashion similar to https://github.com/datalad/datalad-extensions/ and https://github.com/dandi/dandi-api-webshots/ we should have some cron job running which would update some structured (json or yaml) record file and render as a table in README.md something like

## In the wild

Repository | Stars | Dataset | `run` | `containers-run`
----- | ----- | ----- | ----- | -----
https://github.com/cryo-data/QGreenland | 1 | :heavy_check_mark: | :heavy_check_mark: |

## Inner-circle

.... similar for the ones we identify as "ours" -- from `datalad` and some other organizations or explicitly annotated as such

"news feed" could be simply commits (with some descriptive commit message) to this repo ("added X new hits for Y datasets and Z usages of run") which we could then channel to Riot room ;)

- I think majority of those should be discoverable via such queries as
  - `run`: use of `run` https://github.com/search?q=%22DATALAD+RUNCMD%22&type=commits  . 
    - `containers-run`: If search results include actual commit maybe we could even tell if it was using a container if "singularity" or "docker" is in the record.  If not , then I guess we could omit this column for now
  - `Dataset`: being DataLad datasets, and thus modifying `.datalad/config` https://github.com/search?l=&q=%22.datalad%2Fconfig%22+filename%3A.datalad%2Fconfig&type=commits
- may be there is some outside of github service which could assist, otherwise -- could probably be just a search query via API
- may be there is a way to restrict query to not search within already known hits (but still do a full sweep once in a while to do a full update)

To keep in mind
- we might want later to expand to cover https://gin.g-node.org/ (not yet sure if it has API for that ATM, @achilleas-k ?) and  gitlab (https://gitlab.com/search?search=DATALAD+RUNCMD&group_id=&project_id=&snippets=false&repository_ref=&nav_source=navbar suggests that there is no search through commits ATM?)

### PR DESCRIPTION
**Pull request by jwodder**
Closes #1.

Note: The script kept triggering GitHub's abuse detection while searching, so I had to add in a bunch of sleep calls.  Running the script thus ended up taking almost 18 minutes.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Awesome! Can we run it on cron GitHub action?

**Comment by yarikoptic** [comment]
Eg daily

**Comment by jwodder** [comment]
@yarikoptic Scheduled workflow added.

**Comment by jwodder** [comment]
@yarikoptic Note: A GitHub token will need to be added to the repository as a secret named "SEARCH_GITHUB_TOKEN".  I don't believe the presupplied GITHUB_TOKEN has the necessary permissions to perform searches.

**Comment by yarikoptic** [comment]
I will just merge and provide token and comments of any as issues later. Thank you @jwodder , awesome work

**Comment by yarikoptic** [comment]
added the secret, let's see if works ;)

**Pull request merged**
